export interface RecipeType {
  id: number;
  category: string;
  imageFilename: string;
  title: string;
  description: string;
  ingredients: string;
  isGlutenFree: boolean;
  isDairyFree: boolean;
  isSugarFree: boolean;
  stars: number;
  cookingTime: string;
  recipe: string;
  directions: string[];
}

export interface RecipeCategoryType {
  id: number;
  category: string;
  imageFilename: string;
  title: string;
}

export const RecipeCategoriesData = [
  {
    id: 1,
    category: "Type of Dish",
    imageFilename: "snacks.jpg",
    title: "Snacks",
  },
  {
    id: 2,
    category: "Type of Dish",
    imageFilename: "burgers.jpg",
    title: "Burgers",
  },

  {
    id: 3,
    category: "Type of Dish",

    imageFilename: "pizzas.jpg",
    title: "Pizzas",
  },
  {
    id: 4,
    category: "Type of Dish",
    imageFilename: "poke_bowls.jpg",
    title: "Poke Bowls",
  },
  {
    id: 5,
    category: "Type of Dish",
    imageFilename: "salads.jpg",
    title: "Salads",
  },

  {
    id: 6,
    category: "Meal Times",
    imageFilename: "wraps.jpg",
    title: "Breakfast",
  },
  {
    id: 7,
    category: "Meal Times",
    imageFilename: "poke_bowls.jpg",
    title: "Brunch",
  },
  {
    id: 8,
    category: "Meal Times",

    imageFilename: "wraps.jpg",
    title: "Lunch",
  },
  {
    id: 9,
    category: "Meal Times",
    imageFilename: "snacks.jpg",
    title: "Mid Day Sanck",
  },
  {
    id: 10,
    category: "Meal Times",
    imageFilename: "burgers.jpg",
    title: "Dinner",
  },
  {
    id: 11,
    category: "Proteins",
    imageFilename: "steak.jpg",
    title: "Steak",
  },
  {
    id: 12,
    category: "Proteins",
    imageFilename: "sea-bass.jpg",
    title: "Sea Bass",
  },

  {
    id: 14,
    category: "Proteins",
    imageFilename: "ribs.jpg",
    title: "Pork Ribs",
  },
  {
    id: 15,
    category: "Proteins",
    imageFilename: "steak.jpg",
    title: "Lamb",
  },
  {
    id: 16,
    category: "Proteins",
    imageFilename: "shrimp.jpg",
    title: "Shrimp",
  },
  {
    id: 17,
    category: "Proteins",
    imageFilename: "bacon.jpg",
    title: "Bacon",
  },
  {
    id: 18,
    category: "Proteins",
    imageFilename: "salmon.jpg",
    title: "Salmon",
  },
  {
    id: 19,
    category: "Salads",
    imageFilename: "salad_4.jpg",
    title: "Salads",
  },
  {
    id: 20,
    category: "Salads",
    imageFilename: "salad_8.jpg",
    title: "Salads",
  },
  {
    id: 21,
    category: "Salads",
    imageFilename: "salad_3.jpg",
    title: "Salads",
  },
  {
    id: 22,
    category: "Salads",
    imageFilename: "salad_1.jpg",
    title: "Salads",
  },
  {
    id: 23,
    category: "Salads",
    imageFilename: "salad_5.jpg",
    title: "Salads",
  },
  {
    id: 24,
    category: "Salads",
    imageFilename: "salad_2.jpg",
    title: "Salads",
  },
  {
    id: 25,
    category: "Salads",
    imageFilename: "salad_7.jpg",
    title: "Salads",
  },
  {
    id: 26,
    category: "Saldads",
    imageFilename: "fruit_salad.jpg",
    title: "Fruit Salad",
  },
  {
    id: 27,
    category: "Salads",
    imageFilename: "salad_9.jpg",
    title: "Salads",
  },
  {
    id: 28,
    category: "Salads",
    imageFilename: "salad_10.jpg",
    title: "Saladized",
  },
  {
    id: 29,
    category: "Salads",
    imageFilename: "salad_6.jpg",
    title: "Salads",
  },
];

export const RecipesData = [
  {
    id: 1,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_1.jpg",
    title: "Organic Pesto Pizza",
    description: "The most delicious organic pesto pizza you've ever eaten, with tomatoes and feta.",
    ingredients: "pesto, tomato, feta, red peppers, basil, rosemary, thyme",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: true,
    stars: 4,
    cookingTime: "20 minutes",
    recipe:
      "A delightful combination of homemade or store-bought gluten-free pesto spread on a gluten-free crust, topped with fresh tomatoes, feta cheese, red peppers, and a mix of basil, rosemary, and thyme.",
    directions: [
      "Preheat your oven to 475°F (245°C).",
      "Spread a generous layer of gluten-free pesto over a gluten-free pizza base.",
      "Add thinly sliced tomatoes and diced red peppers evenly over the pesto.",
      "Sprinkle crumbled feta cheese and herbs on top.",
      "Bake for 15-20 minutes until the edges are crisp and golden.",
      "Let it cool slightly before cutting into slices. Serve warm.",
    ],
  },
  {
    id: 2,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_2.jpg",
    title: "Classic Margherita Pizza",
    description: "A timeless favorite, featuring fresh mozzarella, tomatoes, and basil.",
    ingredients: "mozzarella, tomato sauce, fresh basil, olive oil, salt",
    isGlutenFree: false,
    isDairyFree: false,
    isSugarFree: true,
    stars: 5,
    cookingTime: "15 minutes",
    recipe:
      "Simple and elegant, this pizza uses a classic dough base, topped with sugo (a simple tomato sauce), slices of fresh mozzarella, fresh basil leaves, and a final drizzle of olive oil.",
    directions: [
      "Heat your oven to its highest setting, around 500°F (260°C) or higher if possible.",
      "Spread a thin layer of sugo over your pizza dough.",
      "Arrange slices of fresh mozzarella and fresh basil leaves on top.",
      "Drizzle a bit of olive oil and sprinkle a pinch of salt over the pizza.",
      "Bake for 10-15 minutes until the crust is golden and the cheese is bubbling.",
      "Slice and serve immediately.",
    ],
  },
  {
    id: 3,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_3.jpg",
    title: "BBQ Chicken Pizza",
    description: "A sweet and smoky BBQ sauce base with grilled chicken, onions, and cilantro.",
    ingredients: "BBQ sauce, cooked chicken, red onion, cilantro, mozzarella, cheddar",
    isGlutenFree: false,
    isDairyFree: false,
    isSugarFree: true,
    stars: 3,
    cookingTime: "25 minutes",
    recipe:
      "Featuring a sugar-free BBQ sauce as the base, this pizza is topped with grilled chicken, thinly sliced red onions, and a blend of mozzarella and cheddar, all finished with fresh cilantro.",
    directions: [
      "Preheat your oven to 450°F (232°C).",
      "Spread a thin layer of sugar-free BBQ sauce over your pizza dough.",
      "Top with shredded cooked chicken and thinly sliced red onions.",
      "Sprinkle a mix of shredded mozzarella and cheddar cheeses on top.",
      "Bake for 20-25 minutes, until the cheese is bubbling and the crust is crispy.",
      "Garnish with fresh cilantro leaves after baking. Slice and serve hot.",
    ],
  },
  {
    id: 4,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_4.jpg",
    title: "Hawaiian Pizza",
    description: "A controversial classic that combines sweet pineapple with ham over mozzarella.",
    ingredients: "pineapple, ham, mozzarella, tomato sauce",
    isGlutenFree: false,
    isDairyFree: false,
    isSugarFree: false,
    stars: 5,
    cookingTime: "22 minutes",
    recipe:
      "A classic favorite, this pizza layers slices of ham and chunks of pineapple over a bed of mozzarella, all atop a traditional pizza sauce and crust.",
    directions: [
      "Preheat your oven to 475°F (245°C).",
      "Spread a base layer of pizza sauce over your dough.",
      "Evenly distribute slices of ham and chunks of pineapple over the sauce.",
      "Cover generously with shredded mozzarella cheese.",
      "Bake for 18-22 minutes until the crust is golden and cheese is bubbling.",
      "Allow to cool for a few minutes, then slice and serve.",
    ],
  },
  {
    id: 5,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_5.jpg",
    title: "Meat Lovers' Pizza",
    description: "Packed with pepperoni, sausage, ham, bacon, and beef, a must-try for meat enthusiasts.",
    ingredients: "pepperoni, sausage, ham, bacon, beef, mozzarella, tomato sauce",
    isGlutenFree: false,
    isDairyFree: false,
    isSugarFree: true,
    stars: 5,
    cookingTime: "25 minutes",
    recipe:
      "A hearty feast of meats including pepperoni, sausage, ham, bacon, and beef, topped with mozzarella on a classic crust, with a sugar-free tomato sauce.",
    directions: [
      "Preheat oven to 450°F (232°C).",
      "Spread sugar-free tomato sauce over a regular pizza dough base.",
      "Layer with sliced pepperoni, sausage, ham, bacon, and ground beef.",
      "Top with shredded mozzarella cheese.",
      "Bake for 20-25 minutes until the crust is golden and the cheese is bubbling.",
      "Let cool for a few minutes, then slice and serve.",
    ],
  },
  {
    id: 6,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_6.jpg",
    title: "Veggie Delight Pizza",
    description: "A garden of seasonal vegetables topped with mozzarella on a crispy crust.",
    ingredients: "bell peppers, onions, mushrooms, black olives, tomatoes, mozzarella, tomato sauce",
    isGlutenFree: false,
    isDairyFree: false,
    isSugarFree: true,
    stars: 4,
    cookingTime: "20 minutes",
    recipe:
      "A vibrant array of bell peppers, onions, mushrooms, black olives, and tomatoes, topped with mozzarella on a classic crust and sugar-free tomato sauce.",
    directions: [
      "Preheat oven to 475°F (245°C).",
      "Spread sugar-free tomato sauce on a regular pizza dough.",
      "Top with sliced bell peppers, onions, mushrooms, black olives, and diced tomatoes.",
      "Cover with shredded mozzarella cheese.",
      "Bake for 15-20 minutes until vegetables are tender and cheese is golden.",
      "Cool slightly, then serve.",
    ],
  },
  {
    id: 7,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_7.jpg",
    title: "Buffalo Chicken Pizza",
    description: "Spicy buffalo chicken, blue cheese, and celery bits for a hot and tangy flavor.",
    ingredients: "buffalo sauce, cooked chicken, blue cheese, mozzarella, celery",
    isGlutenFree: false,
    isDairyFree: true,
    isSugarFree: true,
    stars: 4,
    cookingTime: "20 minutes",
    recipe:
      "Spicy and tangy with buffalo sauce, topped with dairy-free versions of blue and mozzarella cheeses, cooked chicken, and a crisp celery finish.",
    directions: [
      "Preheat oven to 450°F (232°C).",
      "Spread dairy-free buffalo sauce over regular pizza dough.",
      "Add cooked chicken pieces and dairy-free blue cheese crumbles.",
      "Top with dairy-free mozzarella cheese.",
      "Bake for 18-20 minutes until the crust is crispy and the cheese is melted.",
      "Garnish with diced celery before serving.",
    ],
  },
  {
    id: 8,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_8.jpg",
    title: "Four Cheese Pizza",
    description: "A cheesy blend of mozzarella, parmesan, gorgonzola, and ricotta on a thin crust.",
    ingredients: "mozzarella, parmesan, gorgonzola, ricotta, tomato sauce",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: true,
    stars: 5,
    cookingTime: "18 minutes",
    recipe:
      "This gluten-free crust pizza is topped with a rich combination of mozzarella, parmesan, gorgonzola, and ricotta cheeses, making it a cheese lover's delight.",
    directions: [
      "Preheat oven to 475°F (245°C).",
      "Spread a thin layer of tomato sauce over a gluten-free pizza base.",
      "Generously top with shredded mozzarella, grated parmesan, crumbled gorgonzola, and dollops of ricotta cheese.",
      "Bake for 15-18 minutes until the crust is crispy and the cheeses are golden and bubbly.",
      "Let it cool for a few minutes, then slice and serve.",
    ],
  },
  {
    id: 9,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_9.jpg",
    title: "Truffle Mushroom Pizza",
    description: "Earthy mushrooms and truffle oil on a bed of white sauce and mozzarella.",
    ingredients: "mushrooms, truffle oil, mozzarella, white sauce, garlic, parsley",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: false,
    stars: 5,
    cookingTime: "20 minutes",
    recipe:
      "This gourmet pizza features a gluten-free crust topped with a creamy white sauce, earthy mushrooms, mozzarella, a drizzle of truffle oil, and a sprinkle of garlic and parsley for an elegant finish.",
    directions: [
      "Preheat oven to 450°F (232°C).",
      "Spread white sauce evenly over a gluten-free pizza base.",
      "Top with sliced mushrooms and shredded mozzarella cheese.",
      "Drizzle with truffle oil and sprinkle minced garlic and parsley over the top.",
      "Bake for 18-20 minutes until the crust is golden and toppings are fragrant.",
      "Slice and serve immediately, enjoying the luxurious blend of flavors.",
    ],
  },
  {
    id: 10,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_12.jpg",
    title: "Spinach and Goat Cheese Pizza",
    description: "Creamy goat cheese and spinach over a crispy crust, with a hint of garlic.",
    ingredients: "spinach, goat cheese, mozzarella, garlic, olive oil",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: true,
    stars: 4,
    cookingTime: "20 minutes",
    recipe:
      "A healthy and flavorful pizza on a gluten-free crust, featuring a rich layer of spinach, crumbled goat cheese, mozzarella, and a touch of garlic, all finished with a drizzle of olive oil.",
    directions: [
      "Preheat oven to 475°F (245°C).",
      "Brush a gluten-free pizza base lightly with olive oil and garlic.",
      "Spread a layer of fresh spinach leaves across the crust.",
      "Top with crumbled goat cheese and shredded mozzarella.",
      "Bake for 18-20 minutes until the cheese is melted and the crust is crisp.",
      "Slice, serve, and savor the blend of creamy goat cheese and vibrant spinach.",
    ],
  },
  {
    id: 11,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_11.jpg",
    title: "Pepperoni Pizza",
    description: "The classic American pizza with a generous topping of pepperoni slices.",
    ingredients: "pepperoni, mozzarella, tomato sauce",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: true,
    stars: 0,
    cookingTime: "18 minutes",
    recipe:
      "A timeless favorite, this gluten-free crust pizza is layered with a sugar-free tomato sauce, topped with loads of mozzarella and pepperoni slices for a crispy, cheesy delight.",
    directions: [
      "Preheat oven to 475°F (245°C).",
      "Spread a layer of sugar-free tomato sauce over a gluten-free pizza dough.",
      "Cover with shredded mozzarella cheese and arrange pepperoni slices on top.",
      "Bake for 16-18 minutes until the cheese is bubbly and the crust is golden brown.",
      "Wait a few minutes before slicing to let the cheese set. Serve hot and enjoy.",
    ],
  },
  {
    id: 12,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_10.jpg",
    title: "Taco Pizza",
    description:
      "A Mexican-inspired pizza with ground beef, lettuce, tomatoes, and cheese, served with a side of salsa.",
    ingredients: "ground beef, lettuce, tomato, cheddar, mozzarella, taco seasoning, salsa",
    isGlutenFree: false,
    isDairyFree: true,
    isSugarFree: true,
    stars: 3,
    cookingTime: "22 minutes",
    recipe:
      "This pizza merges the flavors of a taco on a traditional crust, featuring spiced ground beef, crisp lettuce, fresh tomatoes, and a blend of dairy-free cheddar and mozzarella, with a side of salsa.",
    directions: [
      "Preheat oven to 475°F (245°C).",
      "Spread a base layer of dairy-free cheese on your pizza dough.",
      "Top with cooked ground beef seasoned with taco seasoning.",
      "Bake for 20-22 minutes until the crust is golden and cheese is melted.",
      "After baking, add fresh lettuce and diced tomatoes on top.",
      "Serve with a side of salsa.",
    ],
  },
  {
    id: 13,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_13.jpg",
    title: "Mediterranean Pizza",
    description:
      "Kalamata olives, feta cheese, and sun-dried tomatoes bring the flavors of the Mediterranean to this pizza.",
    ingredients: "Kalamata olives, feta, sun-dried tomatoes, red onion, mozzarella, spinach",
    isGlutenFree: true,
    isDairyFree: true,
    isSugarFree: true,
    stars: 2,
    cookingTime: "20 minutes",
    recipe:
      "A gluten-free and dairy-free pizza inspired by Mediterranean flavors, featuring Kalamata olives, dairy-free feta, sun-dried tomatoes, red onions, dairy-free mozzarella, and a bed of spinach.",
    directions: [
      "Preheat oven to 450°F (232°C).",
      "Layer the gluten-free pizza base with spinach leaves.",
      "Top with dairy-free mozzarella, chopped Kalamata olives, sun-dried tomatoes, and thinly sliced red onions.",
      "Crumble dairy-free feta cheese over the top.",
      "Bake for 18-20 minutes until the edges are crispy and toppings are heated through.",
      "Slice and enjoy a taste of the Mediterranean.",
    ],
  },
  {
    id: 14,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_14.jpg",
    title: "White Pizza",
    description: "A sauceless pie with ricotta, mozzarella, and parmesan cheeses, seasoned with garlic and olive oil.",
    ingredients: "ricotta, mozzarella, parmesan, garlic, olive oil",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: false,
    stars: 5,
    cookingTime: "20 minutes",
    recipe:
      "Featuring a gluten-free crust lightly brushed with olive oil and garlic, topped with ricotta, mozzarella, and parmesan cheeses for a rich and creamy experience.",
    directions: [
      "Preheat oven to 475°F (245°C).",
      "Brush a gluten-free pizza base with olive oil and minced garlic.",
      "Spread dollops of ricotta cheese evenly over the base.",
      "Sprinkle shredded mozzarella and grated parmesan cheeses on top.",
      "Bake for 18-20 minutes until the crust is golden and cheeses are melted and lightly browned.",
      "Slice and serve this creamy, comforting pizza.",
    ],
  },
  {
    id: 15,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_15.jpg",
    title: "Sausage and Peppers Pizza",
    description: "Italian sausage and roasted bell peppers over a bed of mozzarella cheese.",
    ingredients: "Italian sausage, bell peppers, mozzarella, tomato sauce",
    isGlutenFree: false,
    isDairyFree: false,
    isSugarFree: true,
    stars: 1,
    cookingTime: "25 minutes",
    recipe:
      "This classic pizza features a traditional crust topped with sugar-free tomato sauce, mozzarella cheese, savory Italian sausage, and sweet roasted bell peppers.",
    directions: [
      "Preheat oven to 450°F (232°C).",
      "Spread sugar-free tomato sauce over your pizza dough.",
      "Top with shredded mozzarella cheese.",
      "Add cooked slices of Italian sausage and sliced bell peppers.",
      "Bake for 20-25 minutes until the crust is crispy and the cheese is golden.",
      "Slice and serve hot, enjoying the hearty flavors of sausage and peppers.",
    ],
  },
  {
    id: 16,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_16.jpg",
    title: "Bacon and Egg Breakfast Pizza",
    description: "A breakfast twist with bacon, eggs, and cheese over a white sauce base.",
    ingredients: "bacon, eggs, mozzarella, white sauce, chives",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: true,
    stars: 3,
    cookingTime: "23 minutes",
    recipe:
      "A gluten-free crust forms the base for this innovative breakfast pizza, featuring a creamy white sauce, crispy bacon, softly baked eggs, and mozzarella, all garnished with fresh chives.",
    directions: [
      "Preheat oven to 425°F (220°C).",
      "Spread white sauce over a gluten-free pizza base.",
      "Sprinkle shredded mozzarella cheese around the edges, leaving space in the middle for the eggs.",
      "Crack eggs into the center and arrange bacon slices around them.",
      "Bake for 20-23 minutes, until the egg whites are set but yolks remain runny, and the bacon is crispy.",
      "Garnish with chopped chives, slice, and serve.",
    ],
  },
  {
    id: 17,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_17.jpg",
    title: "Philly Cheesesteak Pizza",
    description: "Thinly sliced steak, onions, mushrooms, and green peppers with a mozzarella and provolone blend.",
    ingredients: "steak, onions, mushrooms, green peppers, mozzarella, provolone, white sauce",
    isGlutenFree: true,
    isDairyFree: true,
    isSugarFree: true,
    stars: 1,
    cookingTime: "25 minutes",
    recipe:
      "This pizza takes the essence of a Philly cheesesteak and presents it on a gluten-free and dairy-free crust, topped with thinly sliced steak, onions, mushrooms, green peppers, and a dairy-free cheese blend.",
    directions: [
      "Preheat oven to 450°F (232°C).",
      "Layer a gluten-free pizza base with dairy-free white sauce.",
      "Top with dairy-free mozzarella and provolone cheeses.",
      "Add thinly sliced steak, sliced onions, mushrooms, and green peppers.",
      "Bake for 22-25 minutes until the crust is golden and toppings are cooked through.",
      "Slice and serve, offering a slice of Philly in every bite.",
    ],
  },
  {
    id: 18,
    category: "Pizzas",
    imageFilename: "/pizzas/pizza_18.jpg",
    title: "Sweet Potato and Kale Pizza",
    description: "A healthful combination of sweet potato, kale, and red onion, finished with a sprinkle of feta.",
    ingredients: "sweet potato, kale, red onion, feta, mozzarella, olive oil, garlic",
    isGlutenFree: true,
    isDairyFree: true,
    isSugarFree: false,
    stars: 2,
    cookingTime: "30 minutes",
    recipe:
      "A nutrient-packed pizza on a gluten-free and dairy-free crust, adorned with roasted sweet potato, kale, and red onion, complemented by dairy-free feta, and brought together with a hint of garlic-infused olive oil.",
    directions: [
      "Preheat oven to 425°F (220°C).",
      "Toss diced sweet potato in olive oil and roast for 10 minutes until slightly soft.",
      "Spread a thin layer of olive oil and minced garlic over a gluten-free pizza base.",
      "Arrange roasted sweet potato, torn kale leaves, and sliced red onion on the base.",
      "Sprinkle with dairy-free mozzarella and feta cheeses.",
      "Bake for 20 minutes, until the crust is crispy and the kale is slightly crispy.",
      "Serve warm, enjoying the blend of sweet and savory with a healthy twist.",
    ],
  },
  {
    id: 19,
    category: "Salads",
    imageFilename: "/salads/salad_1.jpg",
    title: "Caesar Salad",
    description: "Classic Caesar salad with romaine lettuce, parmesan cheese, croutons, and Caesar dressing.",
    ingredients: "romaine lettuce, parmesan cheese, croutons, Caesar dressing",
    isGlutenFree: false,
    isDairyFree: false,
    isSugarFree: true,
    stars: 4,
    cookingTime: "10 minutes",
    recipe: "Crisp romaine lettuce tossed with Parmesan cheese, crunchy croutons, and a creamy Caesar dressing.",
    directions: [
      "Toss chopped romaine lettuce with Caesar dressing.",
      "Add parmesan cheese and croutons.",
      "Mix well and serve chilled.",
    ],
  },
  {
    id: 20,
    category: "Salads",
    imageFilename: "/salads/salad_2.jpg",
    title: "Greek Salad",
    description:
      "A refreshing salad with cucumber, tomatoes, red onion, feta cheese, and olives, dressed with olive oil.",
    ingredients: "cucumber, tomatoes, red onion, feta cheese, olives, olive oil",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: true,
    stars: 4.5,
    cookingTime: "15 minutes",
    recipe:
      "A vibrant mix of cucumber, tomatoes, red onion, and olives, topped with feta cheese and olive oil dressing.",
    directions: [
      "Combine cucumber, tomatoes, red onion, and olives in a bowl.",
      "Top with feta cheese and drizzle with olive oil.",
      "Toss gently to combine and serve.",
    ],
  },
  {
    id: 21,
    category: "Salads",
    imageFilename: "/salads/salad_3.jpg",
    title: "Cobb Salad",
    description: "A hearty salad with chicken, bacon, eggs, avocado, blue cheese, tomatoes, and mixed greens.",
    ingredients: "chicken, bacon, eggs, avocado, blue cheese, tomatoes, mixed greens",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: true,
    stars: 5,
    cookingTime: "20 minutes",
    recipe: "Layered with chicken, bacon, hard-boiled eggs, avocado, and blue cheese over a bed of mixed greens.",
    directions: [
      "Grill chicken and cook bacon until crispy.",
      "Chop hard-boiled eggs, avocado, and tomatoes.",
      "Arrange all ingredients over mixed greens.",
      "Top with blue cheese and serve with your choice of dressing.",
    ],
  },
  {
    id: 22,
    category: "Salads",
    imageFilename: "/salads/salad_4.jpg",
    title: "Nicoise Salad",
    description: "A French salad with tuna, green beans, potatoes, eggs, and olives, with a lemon vinaigrette.",
    ingredients: "tuna, green beans, potatoes, eggs, olives, lemon vinaigrette",
    isGlutenFree: true,
    isDairyFree: true,
    isSugarFree: true,
    stars: 4,
    cookingTime: "25 minutes",
    recipe: "Tuna, green beans, potatoes, and eggs, garnished with olives and dressed in lemon vinaigrette.",
    directions: [
      "Boil potatoes and green beans until tender.",
      "Mix with canned tuna, sliced hard-boiled eggs, and olives.",
      "Dress with lemon vinaigrette and serve.",
    ],
  },
  {
    id: 23,
    category: "Salads",
    imageFilename: "/salads/salad_5.jpg",
    title: "Waldorf Salad",
    description: "A fruity and nutty salad with apples, grapes, celery, walnuts, and mayonnaise dressing.",
    ingredients: "apples, grapes, celery, walnuts, mayonnaise",
    isGlutenFree: true,
    isDairyFree: false,
    isSugarFree: false,
    stars: 3.5,
    cookingTime: "15 minutes",
    recipe: "Crisp apples",
    directions: [
      "Boil potatoes and green beans until tender.",
      "Mix with canned tuna, sliced hard-boiled eggs, and olives.",
      "Dress with lemon vinaigrette and serve.",
    ],
  },
];
